export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #f3e6f8 0%, #fbf7fc 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #e6f0f8 0%, #f7faff 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #fff0f0 0%, #fff7f7 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f0fff4 0%, #f7fff9 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #fef4e6 0%, #fffaf3 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #e6fcf9 0%, #f7fffe 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f9e6fc 0%, #fdf7ff 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #f0f8ff 0%, #f7fbff 100%)' },
];


export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description:
            "Get interview questions and model answers based on your role, experience, and specific focus areas - no with AI-powered detailed explanations"
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description:
            "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
    },
    {
        id: "03",
        title: "Capture Your Insights",
        description:
            "Add personal notes to any question and pin important ones to the top making your learning more organized."
    },
    {
        id: "04",
        title: "Beyond Just Answers",
        description:
            "Understand the 'Why' behind detailed answers with explanations generated by AI, helping you truly master each concept."
    },
    {
        id: "05",
        title: "Unlock Your Potential",
        description:
            "Gain insights and strategies tailored to your unique strengths and weaknesses, empowering you to excel in your interviews."
    },
];