import React, { useState, useMemo, useCallback } from 'react';
import { RefreshCw, CheckCircle, XCircle, ArrowRight, TrendingUp, Send, Search, Briefcase, Award } from 'lucide-react';
import Navbar from '../components/layouts/Navbar';

// --- QUIZ CONFIGURATION ---
const NUMBER_OF_QUESTIONS = 15; 

// The JSON schema is retained as a reference for the mock data structure, but not actively used for generation.
const quizResponseSchema = {
    // ... (Schema definition is kept for reference)
};

// ----------------------------------------------------------------------
// --- MOCK DATA HELPER FUNCTIONS (API REPLACEMENT) ---
// ----------------------------------------------------------------------

/**
 * MOCK: Simulates fetching job opening data and trends.
 * Includes a delay to mimic network latency.
 */
const fetchJobOpenings = async (role) => {
    // Simulate network delay to show the "Searching..." screen
    await new Promise(resolve => setTimeout(resolve, 1500)); 

    const mockText = `
**Current Market Analysis for ${role}**

The market for **${role}** is currently experiencing high demand, especially in areas focusing on cloud-native development and serverless architecture. Companies are prioritizing candidates with strong experience in CI/CD pipelines and microservices.

Key companies currently hiring:
* **Netflix:** Seeking engineers skilled in large-scale distributed systems.
* **Stripe:** Focusing on roles with strong security and API design skills.
* **Google Cloud:** High need for specialists in Kubernetes and multi-cloud environments.
* **Amazon:** Looking for expertise in performance optimization and AWS services.
* **A mid-sized FinTech firm (e.g., Block):** Prioritizing speed and financial compliance knowledge.
    `;

    return { 
        text: mockText, 
        sources: [
            { uri: "https://mockjobsite.com/trends", title: "Top Job Trends Report Q4 2024" },
            { uri: "https://mockhiringblog.io/role-focus", title: "Cloud Hiring Focus" }
        ] 
    };
};


/**
 * MOCK: Simulates generating technical quiz questions.
 * This data replaces the JSON generated by the Gemini API.
 */
const fetchGeneratedQuestions = async (role) => {
    // Simulate network delay to show the "Generating..." screen
    await new Promise(resolve => setTimeout(resolve, 2000)); 

    // Hardcoded quiz questions matching the expected schema structure
    const questions = [
        {
            id: 1,
            question: "What is the primary benefit of using React Hooks over class components in modern React applications?",
            topic: "React",
            correctAnswerId: "c",
            options: [
                { id: "a", text: "They eliminate the need for JSX." },
                { id: "b", text: "They enable synchronous state updates." },
                { id: "c", text: "They allow functional components to use state and lifecycle features." },
                { id: "d", text: "They automatically optimize component rendering performance." }
            ]
        },
        {
            id: 2,
            question: "In SQL, what is the difference between a 'LEFT JOIN' and an 'INNER JOIN'?",
            topic: "Database Querying",
            correctAnswerId: "a",
            options: [
                { id: "a", text: "LEFT JOIN returns all rows from the left table, even if there are no matches in the right table; INNER JOIN returns only matching rows." },
                { id: "b", text: "LEFT JOIN is faster; INNER JOIN is more memory efficient." },
                { id: "c", text: "INNER JOIN allows you to use WHERE clauses, while LEFT JOIN uses only ON clauses." },
                { id: "d", text: "LEFT JOIN requires a primary key; INNER JOIN does not." }
            ]
        },
        {
            id: 3,
            question: "Which HTTP status code indicates that the server successfully fulfilled the request but that there is no content to send in the response payload?",
            topic: "Networking/APIs",
            correctAnswerId: "b",
            options: [
                { id: "a", text: "200 OK" },
                { id: "b", text: "204 No Content" },
                { id: "c", text: "201 Created" },
                { id: "d", text: "304 Not Modified" }
            ]
        },
        {
            id: 4,
            question: "Which of the following data structures is typically used to implement a Least Recently Used (LRU) cache?",
            topic: "Data Structures",
            correctAnswerId: "d",
            options: [
                { id: "a", text: "A Min-Heap and an Array" },
                { id: "b", text: "A Hash Table and a Stack" },
                { id: "c", text: "A Trie and a Queue" },
                { id: "d", text: "A Hash Map and a Doubly Linked List" }
            ]
        },
        {
            id: 5,
            question: "In Python, what is the purpose of the `__init__` method in a class?",
            topic: "Python/OOP",
            correctAnswerId: "b",
            options: [
                { id: "a", text: "To define static methods for the class." },
                { id: "b", text: "It is the constructor, used to initialize an object's state." },
                { id: "c", text: "To define the class inheritance hierarchy." },
                { id: "d", text: "It is used to destroy an object when its lifecycle ends." }
            ]
        },
        // Fill the remaining questions by repeating or adding unique data
        ...Array.from({ length: 10 }).map((_, i) => ({
            id: i + 6,
            question: `Mock Question ${i + 6} specific to the role: ${role}. What is the mock correct answer?`,
            topic: `Mock Topic ${i + 6}`,
            correctAnswerId: ['a', 'b', 'c', 'd'][i % 4],
            options: [
                { id: "a", text: "Mock Option A" },
                { id: "b", text: "Mock Option B" },
                { id: "c", text: "Mock Option C" },
                { id: "d", text: "Mock Option D" }
            ]
        })),
    ];
    
    // Ensure the total number of questions matches the configuration
    return questions.slice(0, NUMBER_OF_QUESTIONS);
};


// ----------------------------------------------------------------------
// --- PHASE 1: APPLICATION & SEARCH COMPONENT ---
// ----------------------------------------------------------------------

const ApplicationForm = ({ onSearch, isSearching }) => {
    const [formData, setFormData] = useState({
        name: '',
        role: 'Front-end Developer',
    });
    const [error, setError] = useState('');

    const roles = ['Front-end Developer', 'Back-end Developer', 'Full-stack Engineer', 'DevOps Engineer', 'Data Scientist', 'Software QA', 'Cloud Architect'];

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
        setError('');
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        if (!formData.name || !formData.role) {
            setError('Please fill in your name and select a role.');
            return;
        }
        onSearch(formData);
    };

    return (
        <div className="bg-white p-6 md:p-8 rounded-2xl shadow-xl transition-all duration-500 w-full max-w-lg">
            <h2 className="text-2xl font-bold text-gray-800 mb-2 flex items-center">
                <Briefcase className="w-6 h-6 mr-2 text-indigo-600"/>
                Career Preparation Hub
            </h2>
            <p className="text-gray-500 mb-6 border-b pb-4">
                Enter your role to get real-time hiring insights and a tailored technical quiz.
            </p>

            <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                    <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">Full Name</label>
                    <input
                        type="text"
                        id="name"
                        name="name"
                        value={formData.name}
                        onChange={handleChange}
                        className="w-full p-3 border border-gray-300 rounded-xl focus:ring-indigo-500 focus:border-indigo-500"
                        placeholder="Jane Doe"
                        required
                        disabled={isSearching}
                    />
                </div>
                
                <div>
                    <label htmlFor="role" className="block text-sm font-medium text-gray-700 mb-1">Target Role</label>
                    <input
                        list="role-suggestions"
                        id="role"
                        name="role"
                        value={formData.role}
                        onChange={handleChange}
                        className="w-full p-3 border border-gray-300 rounded-xl focus:ring-indigo-500 focus:border-indigo-500"
                        placeholder="e.g., Senior React Developer"
                        required
                        disabled={isSearching}
                    />
                    <datalist id="role-suggestions">
                        {roles.map(role => (
                            <option key={role} value={role} />
                        ))}
                    </datalist>
                </div>

                {error && (
                    <p className="text-sm text-red-600 font-medium bg-red-50 p-3 rounded-xl border border-red-200">
                        {error}
                    </p>
                )}

                <button
                    type="submit"
                    disabled={isSearching}
                    className="w-full flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-xl shadow-lg text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-4 focus:ring-green-500 transition-all duration-200 transform hover:scale-[1.01] mt-6 disabled:opacity-50"
                >
                    {isSearching ? (
                        <>
                            <Search className="w-5 h-5 mr-2 animate-pulse" />
                            Searching...
                        </>
                    ) : (
                        <>
                            <Search className="w-5 h-5 mr-2" />
                            Find Companies & Start Prep
                        </>
                    )}
                </button>
            </form>
        </div>
    );
};

// ----------------------------------------------------------------------
// --- PHASE 2: SEARCH RESULTS COMPONENT ---
// ----------------------------------------------------------------------

const SearchResultsScreen = ({ applicantData, results, onStartQuiz, onRestart }) => {
    const { text, sources } = results;

    // Simple markdown to JSX conversion (for list items and paragraphs)
    const renderMarkdown = (markdown) => {
        const lines = markdown.split('\n');
        return lines.map((line, index) => {
            if (line.startsWith('* ')) {
                return <li key={index} className="list-disc ml-6 text-gray-700 text-base">{line.substring(2).trim()}</li>;
            }
            if (line.startsWith('- ')) {
                return <li key={index} className="list-disc ml-6 text-gray-700 text-base">{line.substring(2).trim()}</li>;
            }
            if (line.startsWith('**') && line.endsWith('**')) {
                return <h3 key={index} className="text-xl font-semibold mt-4 mb-2 text-gray-800">{line.replace(/\*\*/g, '').trim()}</h3>;
            }
            if (line.trim() === '') return <br key={index} />;

            return <p key={index} className="mb-3 text-gray-700 leading-relaxed">{line.trim()}</p>;
        });
    };


    return (
        <div className="bg-white p-6 md:p-8 rounded-2xl shadow-xl transition-all duration-500 w-full max-w-3xl">
            <h2 className="text-3xl font-bold text-indigo-600 mb-2">
                Market Insight for **{applicantData.role}**
            </h2>
            <p className="text-gray-500 mb-6 border-b pb-4">
                Analysis generated based on mock data.
            </p>

            <div className="prose max-w-none mb-6">
                {renderMarkdown(text)}
            </div>

            <h3 className="text-lg font-semibold text-gray-700 mt-4 mb-2">Sources</h3>
            <ul className="text-sm space-y-1 mb-6">
                {sources.slice(0, 3).map((source, index) => (
                    <li key={index} className="text-gray-500 truncate">
                        <a href={source.uri} target="_blank" rel="noopener noreferrer" className="text-indigo-500 hover:text-indigo-600 underline">
                            {source.title || source.uri}
                        </a>
                    </li>
                ))}
                {sources.length === 0 && (
                    <li className="text-gray-400 italic">No direct web sources found for the summary.</li>
                )}
            </ul>

            <div className="flex flex-col sm:flex-row justify-between pt-4 border-t space-y-3 sm:space-y-0 sm:space-x-4">
                <button
                    onClick={onRestart}
                    className="flex-1 flex items-center justify-center px-4 py-3 border border-gray-300 text-base font-medium rounded-xl text-gray-700 bg-gray-50 hover:bg-gray-100 transition-all duration-200"
                >
                    <RefreshCw className="w-4 h-4 mr-2" />
                    New Role Search
                </button>
                <button
                    onClick={onStartQuiz}
                    className="flex-1 flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-xl shadow-lg text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-4 focus:ring-indigo-500 transition-all duration-200 transform hover:scale-[1.01]"
                >
                    Start {NUMBER_OF_QUESTIONS} Question Tech Quiz
                    <ArrowRight className="w-5 h-5 ml-2" />
                </button>
            </div>
        </div>
    );
};


// ----------------------------------------------------------------------
// --- CORE QUIZ COMPONENTS ---
// ----------------------------------------------------------------------

const QuestionCard = ({ question, currentQuestionIndex, totalQuestions, selectedAnswer, onSelectAnswer, isAnswered, correctAnswerId }) => {
    const getOptionClasses = useCallback((optionId) => {
        let classes = 'p-3 my-2 rounded-xl cursor-pointer transition-all duration-300 border-2 shadow-md ';
    
        if (!isAnswered) {
            // Unanswered state
            classes += selectedAnswer === optionId
                ? 'bg-indigo-50 border-indigo-500 text-indigo-700 font-semibold scale-[1.02]'
                : 'bg-white border-gray-200 hover:bg-gray-50';
        } else {
            // Answered state
            const isCorrect = optionId === correctAnswerId;
            const isSelected = optionId === selectedAnswer;
    
            if (isCorrect) {
                classes += 'bg-green-100 border-green-500 text-green-800 font-bold'; // Correct answer
            } else if (isSelected && !isCorrect) {
                classes += 'bg-red-100 border-red-500 text-red-800 font-bold'; // Incorrectly selected answer
            } else {
                classes += 'bg-gray-50 border-gray-200 text-gray-500 cursor-default'; // Unselected wrong answer
            }
        }
    
        return classes;
    }, [selectedAnswer, isAnswered, correctAnswerId]);
    
    return (
        <div className="bg-white p-6 md:p-8 rounded-2xl shadow-xl transition-all duration-500 w-full max-w-xl">
            <div className="flex justify-between items-center mb-4 pb-4 border-b border-gray-100">
                <span className="text-xl font-bold text-indigo-600">
                    Question {currentQuestionIndex + 1} / {totalQuestions}
                </span>
                <span className="text-sm font-medium text-gray-500 px-3 py-1 bg-indigo-50 rounded-full">
                    {question.topic || 'General Tech'}
                </span>
            </div>
    
            <h2 className="text-xl md:text-2xl font-semibold mb-6 text-gray-800 leading-relaxed">
                {question.question}
            </h2>
    
            <div className="space-y-3">
                {question.options.map(option => (
                    <div
                        key={option.id}
                        className={getOptionClasses(option.id)}
                        onClick={() => !isAnswered && onSelectAnswer(option.id)}
                    >
                        <span className="mr-3 font-mono text-lg">{option.id.toUpperCase()}.</span>
                        <span className="text-base">{option.text}</span>
                        {/* Display icons for correctness/selection only after answer is submitted */}
                        {isAnswered && option.id === correctAnswerId && (
                            <CheckCircle className="inline ml-2 text-green-600 w-5 h-5" />
                        )}
                        {isAnswered && option.id === selectedAnswer && option.id !== correctAnswerId && (
                            <XCircle className="inline ml-2 text-red-600 w-5 h-5" />
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

// ----------------------------------------------------------------------
// --- NEW CERTIFICATE COMPONENT ---
// ----------------------------------------------------------------------

const Certificate = ({ name, role, score, totalQuestions }) => {
    const today = useMemo(() => new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), []);

    return (
        <div id="certificate-print-area" className="w-full max-w-3xl mx-auto p-10 md:p-16 bg-white border-8 border-indigo-600 shadow-2xl rounded-xl mt-6 transform rotate-0 scale-100 print:border-none print:p-0">
            <style jsx="true">{`
                @media print {
                    @page {
                        size: landscape;
                        margin: 0;
                    }
                    #certificate-print-area {
                        border: none !important;
                        box-shadow: none !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        min-height: 100vh;
                        width: 100vw;
                        background: white;
                    }
                    .no-print {
                        display: none !important;
                    }
                }
                .signature {
                    font-family: 'Inter', cursive; /* Use a readable font for signature */
                    font-size: 2rem;
                }
            `}</style>
            
            <div className="text-center">
                <h3 className="text-3xl font-extrabold text-indigo-800 mb-2 border-b-4 border-indigo-200 inline-block px-4 pb-1">
                    CERTIFICATE OF ACHIEVEMENT
                </h3>
                <p className="text-xl text-gray-600 mt-6">
                    This certifies that
                </p>

                <h1 className="text-6xl font-black text-indigo-700 mt-4 mb-8 py-3 border-b-2 border-dashed border-gray-300 inline-block px-10">
                    {name}
                </h1>

                <p className="text-2xl text-gray-700 font-semibold mb-4">
                    has successfully completed the
                </p>
                
                <p className="text-4xl font-bold text-green-600 mb-8 px-6 py-2 bg-green-50 rounded-lg inline-block">
                    {role} Technical Readiness Assessment
                </p>

                <p className="text-xl text-gray-600 leading-relaxed max-w-md mx-auto">
                    Achieving an outstanding score of **{score} out of {totalQuestions}**, demonstrating a high level of technical competency and readiness in core domain areas.
                </p>

                <div className="flex justify-around items-end mt-12 pt-4 border-t border-gray-300">
                    <div>
                        <p className="signature text-4xl text-gray-800 border-b-2 border-gray-800">
                            The Assessment Team
                        </p>
                        <p className="text-sm text-gray-500 mt-2">
                            Assessment Authority
                        </p>
                    </div>
                    <div>
                        <p className="text-xl font-medium text-gray-700 border-b-2 border-gray-800">
                            {today}
                        </p>
                        <p className="text-sm text-gray-500 mt-2">
                            Date of Completion
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};


const ResultScreen = ({ score, totalQuestions, onRestart, applicantData }) => {
    const percentage = Math.round((score / totalQuestions) * 100);
    const hasCertificate = percentage >= 80;

    const getResultStyle = useMemo(() => {
        if (percentage >= 80) return { bgColor: 'bg-green-500', message: 'Excellent! Ready for the Interview!', icon: Award };
        if (percentage >= 50) return { bgColor: 'bg-yellow-500', message: 'Good effort! Review key topics.', icon: TrendingUp };
        return { bgColor: 'bg-red-500', message: 'Time to study more. You got this!', icon: XCircle };
    }, [percentage]);

    const Icon = getResultStyle.icon;
    
    const handlePrint = () => {
        // Simple print command. Browser print dialog will handle the rest.
        window.print();
    };

    return (
        <div className="flex flex-col items-center w-full max-w-4xl">
            <div className="bg-white p-8 rounded-2xl shadow-2xl w-full max-w-sm text-center">
                <div className={`p-4 rounded-full mx-auto w-24 h-24 flex items-center justify-center mb-6 ${getResultStyle.bgColor}`}>
                    <Icon className="w-12 h-12 text-white" />
                </div>

                <h1 className="text-3xl font-extrabold text-gray-800 mb-2">Quiz Complete!</h1>
                <p className="text-lg text-gray-600 mb-6">{getResultStyle.message}</p>

                <div className="mb-8">
                    <p className="text-5xl font-black text-indigo-600 mb-2">{score}/{totalQuestions}</p>
                    <p className="text-xl font-semibold text-gray-700">
                    ({percentage}%)
                    </p>
                </div>
                
                {hasCertificate && (
                    <div className="mb-6 p-4 bg-green-50 border-2 border-green-300 rounded-xl">
                        <p className="text-lg font-bold text-green-700 flex items-center justify-center">
                            <Award className='w-5 h-5 mr-2'/> Certificate Awarded!
                        </p>
                        <button
                            onClick={handlePrint}
                            className="w-full mt-3 px-4 py-2 text-white bg-green-600 rounded-lg hover:bg-green-700 transition-all text-sm font-medium"
                        >
                            Print Certificate
                        </button>
                    </div>
                )}


                <button
                    onClick={onRestart}
                    className="w-full flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-xl shadow-lg text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-4 focus:ring-indigo-500 transition-all duration-200 transform hover:scale-[1.01]"
                >
                    <RefreshCw className="w-5 h-5 mr-2" />
                    Restart Full Prep Flow
                </button>
            </div>
            
            {hasCertificate && (
                <Certificate
                    name={applicantData.name}
                    role={applicantData.role}
                    score={score}
                    totalQuestions={totalQuestions}
                />
            )}
        </div>
    );
};


// ----------------------------------------------------------------------
// --- MAIN APP COMPONENT ---
// ----------------------------------------------------------------------

export default function Mocktest() {
    const [questions, setQuestions] = useState([]);
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [score, setScore] = useState(0);
    const [selectedAnswer, setSelectedAnswer] = useState(null);
    const [isAnswered, setIsAnswered] = useState(false);
    
    // State for flow control
    const [screen, setScreen] = useState('application'); // 'application', 'searching', 'results', 'quiz_loading', 'quiz', 'quiz_results'
    
    // State for application and search results
    const [applicantData, setApplicantData] = useState(null);
    const [jobResults, setJobResults] = useState(null);
    const [error, setError] = useState(null);

    const currentQuestion = useMemo(() => questions[currentQuestionIndex], [questions, currentQuestionIndex]);
    const totalQuestions = questions.length;
    const isLastQuestion = currentQuestionIndex === totalQuestions - 1;


    // --- HANDLERS ---

    const handleSearchTrigger = useCallback(async (data) => {
        setApplicantData(data);
        setScreen('searching');
        setError(null);

        try {
            // Call MOCK function
            const results = await fetchJobOpenings(data.role);
            setJobResults(results);
            setScreen('results');
        } catch (err) {
            setError(err.message || "An unknown error occurred during the mock job search.");
            setScreen('application'); 
        }
    }, []);
    
    const handleStartQuiz = useCallback(async () => {
        setScreen('quiz_loading');
        setError(null);

        try {
            // Call MOCK function
            const data = await fetchGeneratedQuestions(applicantData.role);
            setQuestions(data);
            setCurrentQuestionIndex(0); // Reset index for new quiz
            setScore(0);
            setSelectedAnswer(null);
            setIsAnswered(false);
            setScreen('quiz');
        } catch (err) {
            setError(err.message || "Failed to generate mock quiz data.");
            setScreen('application');
        }
    }, [applicantData]);

    const handleAnswerSelect = useCallback((answerId) => {
        if (!isAnswered) {
            setSelectedAnswer(answerId);
        }
    }, [isAnswered]);

    const handleSubmitAnswer = useCallback(() => {
        if (!selectedAnswer || isAnswered || !currentQuestion) return;

        setIsAnswered(true);
        if (selectedAnswer === currentQuestion.correctAnswerId) {
            setScore(prevScore => prevScore + 1);
        }
    }, [selectedAnswer, isAnswered, currentQuestion]);

    const handleNextQuestion = useCallback(() => {
        if (!isAnswered) return;

        if (currentQuestionIndex < totalQuestions - 1) {
            setCurrentQuestionIndex(prevIndex => prevIndex + 1);
            setSelectedAnswer(null);
            setIsAnswered(false);
        } else {
            setScreen('quiz_results');
        }
    }, [currentQuestionIndex, totalQuestions, isAnswered]);

    const handleRestart = useCallback(() => {
        // Reset all state for a fresh start (back to application form)
        setQuestions([]);
        setCurrentQuestionIndex(0);
        setScore(0);
        setSelectedAnswer(null);
        setIsAnswered(false);
        setApplicantData(null);
        setJobResults(null);
        setError(null);
        setScreen('application');
    }, []);

    const renderContent = () => {
        if (error) {
            return (
                <div className="text-xl text-red-600 p-10 bg-red-50 rounded-xl shadow-lg border border-red-300 w-full max-w-lg text-center">
                    <p>An error occurred:</p>
                    <p className='text-sm italic mt-2'>{error}</p>
                    <button 
                        onClick={handleRestart} 
                        className="mt-4 px-4 py-2 bg-red-500 text-white rounded-xl hover:bg-red-600 transition-all"
                    >
                        Start Over
                    </button>
                </div>
            );
        }

        switch (screen) {
            case 'application':
                return <ApplicationForm onSearch={handleSearchTrigger} isSearching={false} />;
            
            case 'searching':
                return (
                    <div className="text-2xl font-semibold text-green-600 flex items-center space-x-3 p-10 bg-white rounded-xl shadow-lg w-full max-w-lg">
                        <Search className="animate-pulse w-6 h-6" />
                        <span>Analyzing job market for **{applicantData?.role}**...</span>
                    </div>
                );
            
            case 'results':
                return <SearchResultsScreen applicantData={applicantData} results={jobResults} onStartQuiz={handleStartQuiz} onRestart={handleRestart} />;

            case 'quiz_loading':
                return (
                    <div className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3 p-10 bg-white rounded-xl shadow-lg w-full max-w-lg">
                        <RefreshCw className="animate-spin w-6 h-6" />
                        <span>Generating **{NUMBER_OF_QUESTIONS}** role-specific questions for **{applicantData?.role}**...</span>
                    </div>
                );

            case 'quiz':
                if (!currentQuestion) return null;
                return (
                    <div className="flex flex-col items-center w-full">
                        <QuestionCard
                            question={currentQuestion}
                            currentQuestionIndex={currentQuestionIndex}
                            totalQuestions={totalQuestions}
                            selectedAnswer={selectedAnswer}
                            onSelectAnswer={handleAnswerSelect}
                            isAnswered={isAnswered}
                            correctAnswerId={currentQuestion.correctAnswerId}
                        />
                        <div className="mt-6 w-full max-w-xl flex justify-between">
                            <div className="flex-1 pt-3">
                                <span className="text-sm font-medium text-gray-500">
                                    Score: <span className="text-indigo-600 font-bold">{score}</span>
                                </span>
                            </div>
                            {!isAnswered ? (
                                <button
                                    onClick={handleSubmitAnswer}
                                    disabled={!selectedAnswer}
                                    className="px-6 py-3 text-white font-semibold rounded-xl shadow-md transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-4 focus:ring-green-500 transform hover:scale-[1.01]"
                                >
                                    Submit Answer
                                </button>
                            ) : (
                                <button
                                    onClick={handleNextQuestion}
                                    className="px-6 py-3 text-white font-semibold rounded-xl shadow-md transition-all duration-200 bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-4 focus:ring-indigo-500 transform hover:scale-[1.01] flex items-center"
                                >
                                    {isLastQuestion ? 'View Results' : 'Next Question'}
                                    <ArrowRight className="w-5 h-5 ml-2" />
                                </button>
                            )}
                        </div>
                    </div>
                );

            case 'quiz_results':
                return <ResultScreen score={score} totalQuestions={totalQuestions} onRestart={handleRestart} applicantData={applicantData} />;
            
            default:
                return null;
        }
    };

    return (
        <>
        <Navbar/>
        <div className="min-h-screen bg-gray-100 flex flex-col items-center p-4 md:p-8 font-['Inter']">
            <style>{`
                /* Load Inter Font from Google Fonts */
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');

                .bg-gradient-header {
                    background-image: linear-gradient(135deg, #6366f1 0%, #a78bfa 100%);
                }
                /* Custom styling for markdown list rendering */
                .prose ul {
                    list-style: disc;
                    padding-left: 1.5rem;
                    margin-top: 1rem;
                    margin-bottom: 1rem;
                }
                .prose li {
                    margin-bottom: 0.5rem;
                }
            `}</style>

            <header className="bg-gradient-header text-white p-4 md:p-6 w-full max-w-3xl rounded-xl shadow-2xl mb-10 text-center">
                <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight">
                    <span className='mr-2'>🚀</span> Job Prep Tech Assessment (Mock Mode)
                </h1>
                {applicantData ? (
                    <p className="mt-1 text-indigo-100 text-sm md:text-base">
                        Candidate: <span className="font-semibold">{applicantData.name}</span> | Target Role: <span className="font-semibold">{applicantData.role}</span>
                    </p>
                ) : (
                    <p className="mt-1 text-indigo-100 text-sm md:text-base">
                        Find hiring insights, then take a tailored technical quiz.
                    </p>
                )}
            </header>

            <main className="w-full flex justify-center">
                {renderContent()}
            </main>
        </div>
        </>
    );
}